server:
  servlet:
    session:
      cookie:
        name: SESSION
spring:
  application:
    name: advanced-chat-server
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  modulith:
    runtime:
      verification-enabled: true
vite:
  mode: build
logging:
  level:
    root: info
